### ISSUE TITLE
Не обрабатывается пустое значение в поле авторизации

### ISSUE THREAD

**Issue by polargris** [Jourando/Balakirevka#42]
На главной странице в поле "оператор" ввести пробелы или текст с тегами.
Нажать кнопку "Отправить".

Результат: не выводится ошибка о незаполненном поле.
https://s.mail.ru/KU7M/pcp5wxAaj

**Comment by Jourando** [comment]
3a659fc2757441b6ef96677212685375269ab860 - fix failed; rebuild

**Comment by Jourando** [comment]
5f919e920a6446ba1ba80f073695e27f6e0dc9cf -- fix --> test

**Comment by Jourando** [comment]
rebuild
016be6b4bac13100f6c463313fcb90ecf05edb5b --> test

**Comment by polargris** [comment]
08.11.2017
Ошибка обрабатывается
https://s.mail.ru/F5d7/P4fA16Xsr
