### ISSUE TITLE
Элемент уведомления о включенном capslock кликабелен

### ISSUE THREAD

**Issue by polargris** [Jourando/Balakirevka#43]
Рядом с полем ввода пароля находится иконка нотифайки о включенном капслоке.
Иконка кликабельна.
https://s.mail.ru/Crjm/2142xdwCD

**Comment by Jourando** [comment]
Должно фиксануться на 3a659fc2757441b6ef96677212685375269ab860

--> в тест

**Comment by Jourando** [comment]
done
