### ISSUE TITLE
Иконка уведомления о включенном капсе сбрасывает поле авторизации

### ISSUE THREAD

**Issue by polargris** [Jourando/Balakirevka#44]
Ввести логин и пароль в поле авторизации.
Нажать на иконку капслока https://s.mail.ru/Crjm/2142xdwCD

Результат: сбросится поле с именем оператора.

Ожидание: иконка не должна быть кликабельной (https://github.com/Jourando/Balakirevka/issues/42)
не должно сбрасываться значение в поле авторизации

**Comment by Jourando** [comment]
Должно фиксануться в 3a659fc2757441b6ef96677212685375269ab860

--> в тест

**Comment by Jourando** [comment]
done
