### ISSUE TITLE
Wrong cols in multimode [Tabedit]

### ISSUE THREAD

**Issue by Jourando** [Jourando/Balakirevka#55]
В мультимоде tabedit'a олонки поплыли

Linked to https://github.com/Jourando/Balakirevka/issues/30

**Comment by Jourando** [comment]
https://screenshots.firefox.com/z1aTbZgFgkKaWIkE/test2.ru

**Comment by Jourando** [comment]
Проблема сводится к тому, что в th line1 9 cols, а в th line2 - 10 cols
+лишний edit test

// исправить, не потеряв id

**Comment by Jourando** [comment]
7cd56f52ff47dcf9d8e7587b16c642e149838828 ---> to test

**Comment by Jourando** [comment]
fix failed

**Comment by Jourando** [comment]
4a95faa4dc488ecb900ead1c9e26acfa40422247 ---> test

**Comment by Gr-Field** [comment]
tested

**Comment by Jourando** [comment]
Done
